name: notebooks-ambit
channels:
  - conda-forge
  - default
dependencies:
  - python~=3.5
  - pip
  - requests
  - ipywidgets
  - pandas
  - numpy
  - pyyaml>=5.1
  - qgrid
  - measurement
  - pip:
      - pynanomapper>=1.1.1
