tasks:

  - source: tasks/retrieve.py
    product:
      nb: "products/retrieve.ipynb"
      data: "{{folder_output}}/params.txt"

    params:
      folder_output: "{{folder_output}}"    
      solr_api_url: "{{solr_api_url}}"   
      solr_api_key: "{{solr_api_key}}"   
      query: "{{query}}"

  - source: tasks/retrieve_study_metadata.py
    product:
      nb: "products/retrieve_study_metadata.ipynb"
      data: "{{folder_output}}/pykeen/{{prefix}}study_kgraph.txt"  

    params:
      folder_output: "{{folder_output}}"    
      solr_api_url: "{{solr_api_url}}"   
      solr_api_key: "{{solr_api_key}}"   
      query: "{{query}}"     
      model_embedding: "{{model_embedding}}"
      hnsw_distance: "{{hnsw_distance}}"      
      terms_file :  "{{folder_output}}/terms/{{prefix}}terms.txt" 
      prefix: "{{prefix}}"        
      ann_index : "{{folder_output}}/terms/{{prefix}}{{model_embedding}}_{{hnsw_distance}}_hnswlib.index"    
      annotation_folder: "{{annotation_folder}}"
      study_kgraph_file: "{{folder_output}}/pykeen/{{prefix}}study_kgraph.txt"    

  - source: tasks/retrieve_templates.py
    product:
      nb: "products/retrieve_templates.ipynb"
      data: "{{folder_output}}/templates"

    params:
      folder_output: "{{folder_output}}"    
      templates_pchem: "{{templates_pchem}}"   
     

  - source: tasks/match_params.py
    product:
      nb: "products/match_params.ipynb"
      data: "{{folder_output}}/terms/matched_params.txt"

    params:
      folder_output: "{{folder_output}}"      

  - source: tasks/onto.py
    product:
      nb: "products/onto.ipynb"
      data: "{{folder_output}}/terms"      

    params:
      folder_output: "{{folder_output}}"
      prefix: "{{prefix}}"
      blueprint: "{{blueprint}}"    
      model_embedding: "{{model_embedding}}"
      hnsw_distance: "{{hnsw_distance}}"     
      terms_file :  "{{folder_output}}/terms/{{prefix}}terms.txt"   
      ann_index : "{{folder_output}}/terms/{{prefix}}{{model_embedding}}_{{hnsw_distance}}_hnswlib.index"
      ann_param_hits : "{{folder_output}}/terms/{{prefix}}{{model_embedding}}_{{hnsw_distance}}_params_hits.txt"
      

  - source: tasks/onto_stats.py
    product:
      nb: "products/onto_stats.ipynb"

    params:
      folder_output: "{{folder_output}}"
      model_embedding: "{{model_embedding}}"
      hnsw_distance: "{{hnsw_distance}}"  
      ann_param_hits : "{{folder_output}}/terms/{{prefix}}{{model_embedding}}_{{hnsw_distance}}_params_hits.txt"
      

  - source: tasks/spacy.py
    product:
      nb: "products/spacy.ipynb"

    params:
      folder_output: "{{folder_output}}"
      model_embedding: "{{model_embedding}}"
      hnsw_distance: "{{hnsw_distance}}"    
      documents: "{{documents}}"  
      terms_file :  "{{folder_output}}/terms/{{prefix}}terms.txt" 
      prefix: "{{prefix}}"   
      ann_index : "{{folder_output}}/terms/{{prefix}}{{model_embedding}}_{{hnsw_distance}}_hnswlib.index" 
    

  - source: tasks/kgraph.py
    product:
      nb: "products/kgraph.ipynb"

    params:
      folder_output: "{{folder_output}}"
      model_embedding: "{{model_embedding}}"
      hnsw_distance: "{{hnsw_distance}}"    
      ann_pdf_hits: "{{folder_output}}/terms/{{prefix}}{{model_embedding}}_{{hnsw_distance}}_pdf_nouns.txt"
      prefix: "{{prefix}}"
      study_kgraph_file: "{{folder_output}}/pykeen/{{prefix}}study_kgraph.txt"    


  - source: tasks/scispacy.py
    product:
      nb: "products/scispacy.ipynb"

    params:
      folder_output: "{{folder_output}}"
      documents: "{{documents}}"      
      scispacy_enable: "{{scispacy_enable}}"   

  - source: tasks/overview.py
    product:
      nb: "products/overview.ipynb"     

    params:
      folder_output: "{{folder_output}}" 
      solr_api_url: "{{solr_api_url}}"   
      solr_api_key: "{{solr_api_key}}"     
      annotation_folder: "{{annotation_folder}}"  
      query: "{{query}}"     
      plot_dose_response: "{{plot_dose_response}}"   
      
  - source: tasks/blueprint.py
    product:
      nb: "products/blueprint.ipynb"  
      data: "{{folder_output}}/terms/blueprint.json"   

    params:
      folder_output: "{{folder_output}}" 
      blueprint: "{{blueprint}}"       
 
  - source: tasks/templates2kgraph.py
    product:
      nb: "products/templates2kgraph.ipynb"

    params:
      folder_output: "{{folder_output}}"
      model_embedding: "{{model_embedding}}"
      hnsw_distance: "{{hnsw_distance}}"     
      terms_file :  "{{folder_output}}/terms/{{prefix}}terms.txt" 
      prefix: "{{prefix}}"   
      ann_index : "{{folder_output}}/terms/{{prefix}}{{model_embedding}}_{{hnsw_distance}}_hnswlib.index" 
      spreadsheets: "{{spreadsheets}}"
      terms_file :  "{{folder_output}}/terms/{{prefix}}terms.txt"       
    




